# Generated by Django 3.0.8 on 2020-08-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='youtube_video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
