# Generated by Django 3.0.8 on 2020-08-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20200809_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('skills', models.ManyToManyField(to='base.Technologies')),
            ],
        ),
    ]
