# Generated by Django 3.0.8 on 2020-08-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_skillcat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='technologies',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project',
            field=models.ManyToManyField(blank=True, null=True, to='base.Port_Project'),
        ),
    ]
