# Generated by Django 3.0.8 on 2020-08-09 18:33

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20200809_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='port_project',
            old_name='decription',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='port_project',
            name='video',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
